// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patlus.IdentityManagement.Persistence.Contexts;

namespace Patlus.IdentityManagement.Persistence.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20191012090120_Iniil Strctre")]
    partial class IniilStrctre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Patlus.IdentityManagement.UseCase.Entities.HostedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HostedAccount");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90fdc79d-b97a-4b62-9c04-5b2f94df2026"),
                            Archived = false,
                            CreatedTime = new DateTime(2019, 10, 12, 9, 1, 19, 928, DateTimeKind.Utc).AddTicks(2220),
                            CreatorId = new Guid("90fdc79d-b97a-4b62-9c04-5b2f94df2026"),
                            LastModifiedTime = new DateTime(2019, 10, 12, 9, 1, 19, 928, DateTimeKind.Utc).AddTicks(2938),
                            Name = "root",
                            Password = "YRktoPpuxUe8JlLYP5QC1qOuC7/JoUcJ4bjZmw6cpXU="
                        });
                });

            modelBuilder.Entity("Patlus.IdentityManagement.UseCase.Entities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PoolId")
                        .IsUnique();

                    b.ToTable("Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90fdc79d-b97a-4b62-9c04-5b2f94df2026"),
                            Active = true,
                            Archived = false,
                            CreatedTime = new DateTime(2019, 10, 12, 9, 1, 19, 917, DateTimeKind.Utc).AddTicks(5068),
                            CreatorId = new Guid("90fdc79d-b97a-4b62-9c04-5b2f94df2026"),
                            LastModifiedTime = new DateTime(2019, 10, 12, 9, 1, 19, 917, DateTimeKind.Utc).AddTicks(5714),
                            Name = "root",
                            PoolId = new Guid("c73d72b1-326d-4213-ab11-ba47d83b9ccf")
                        });
                });

            modelBuilder.Entity("Patlus.IdentityManagement.UseCase.Entities.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pool");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c73d72b1-326d-4213-ab11-ba47d83b9ccf"),
                            Active = true,
                            Archived = false,
                            CreatedTime = new DateTime(2019, 10, 12, 9, 1, 19, 915, DateTimeKind.Utc).AddTicks(5242),
                            CreatorId = new Guid("90fdc79d-b97a-4b62-9c04-5b2f94df2026"),
                            Description = "Default identity pool for system administrator.",
                            LastModifiedTime = new DateTime(2019, 10, 12, 9, 1, 19, 915, DateTimeKind.Utc).AddTicks(6338),
                            Name = "System Administrator"
                        });
                });

            modelBuilder.Entity("Patlus.IdentityManagement.UseCase.Entities.Identity", b =>
                {
                    b.HasOne("Patlus.IdentityManagement.UseCase.Entities.HostedAccount", "HostedAccount")
                        .WithOne("Identity")
                        .HasForeignKey("Patlus.IdentityManagement.UseCase.Entities.Identity", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patlus.IdentityManagement.UseCase.Entities.Pool", "Pool")
                        .WithOne()
                        .HasForeignKey("Patlus.IdentityManagement.UseCase.Entities.Identity", "PoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
